[workspace]

[package]
name = "sdl3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl3-sys = { path = "sdl3-sys" }
