[package]
name = "sdl3-sys"
version = "0.1.0"
edition = "2021"
links = "SDL3"

[features]
bundled = []

[build-dependencies]
bindgen = "0.66.1"
cfg-if = "1.0.0"
cmake = "0.1.50"
pkg-config = "0.3.27"
