name: generate-bindgen
run-name: Generate bindgen
on: [push]
jobs:
  generate-bindgen-x86_64-unknown-linux-gnu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add x86_64-unknown-linux-gnu
      - run: rustup update
      - run: cd ./sdl3-bindgen && ./run-ga.sh x86_64-unknown-linux-gnu
      - uses: actions/upload-artifact@v4
        with:
          name: bindings_x86_64-unknown-linux-gnu.rs
          path: ./sdl3-bindgen/bindings_x86_64-unknown-linux-gnu.rs
          if-no-files-found: error
