name: generate-all-bindings
run-name: Generate all bindings

on:
  push:
    paths:
      - sdl3-bindgen/**
  workflow_call:

jobs:
  generate-bindings-x86_64-unknown-linux-gnu:
    uses: ./.github/workflows/generate-bindgen.yml
    with:
      os: ubuntu-latest
      target: x86_64-unknown-linux-gnu

  generate-bindings-x86_64-pc-windows-msvc:
    uses: ./.github/workflows/generate-bindgen.yml
    with:
      os: windows-latest
      target: x86_64-pc-windows-msvc

  generate-bindings-aarch64-apple-darwin:
    uses: ./.github/workflows/generate-bindgen.yml
    with:
      os: macos-latest
      target: aarch64-apple-darwin
